services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: dpp
      POSTGRES_PASSWORD: dpp
      POSTGRES_DB: dpp
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dpp -d dpp"]
      interval: 5s
      retries: 20

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio12345
    ports: ["9000:9000", "9001:9001"]
    volumes: [ "minio:/data" ]

  immudb:
    image: codenotary/immudb:latest
    ports: ["3322:3322"]
    healthcheck:
      test: ["CMD", "immuclient", "health"]

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./seed/keycloak-realm-export.json:/opt/keycloak/data/import/realm.json
    ports: ["8080:8080"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/realms/master/.well-known/openid-configuration"]
      interval: 5s
      retries: 30

  opa:
    build: ./opa
    ports: ["8181:8181"]
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8181/health"]


  api:
    build: ./api
    environment:
      DATABASE_URL: postgresql+psycopg://dpp:dpp@postgres:5432/dpp
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio12345
      OIDC_ISSUER_URL: http://keycloak:8080/realms/dpp
      OIDC_AUDIENCE: dpp-api
      OPA_URL: http://opa:8181/v1/data/dpp/allow
      IMMUDb_ADDR: immudb:3322
    depends_on: [postgres, minio, keycloak, opa, immudb]
    ports: ["8000:8000"]

  portal:
    build: ./portal
    environment:
      NEXT_PUBLIC_OIDC_ISSUER: http://localhost:8080/realms/dpp
      NEXT_PUBLIC_CLIENT_ID: dpp-portal
      API_BASE: http://localhost:8000
    depends_on: [api]
    ports: ["3000:3000"]

  # Optional event bus, off by default
  # redpanda:
  #   image: redpandadata/redpanda:latest
  #   command: redpanda start --mode dev-container --overprovisioned --smp 1 --memory 512M
  #   ports: ["9092:9092"]

volumes:
  pgdata:
  minio:
