# Setup Portal for Local Development
# This script sets up the Portal Node.js environment and creates necessary config files

Write-Host "🔧 Setting up Portal for Local Development" -ForegroundColor Cyan
Write-Host ""

$portalPath = Join-Path $PSScriptRoot "portal"

# Check if we're in the right directory
if (-not (Test-Path $portalPath)) {
    Write-Host "✗ Portal directory not found at: $portalPath" -ForegroundColor Red
    exit 1
}

Set-Location $portalPath

# Check if Node.js is installed
Write-Host "Checking for Node.js..." -ForegroundColor Yellow
try {
    $nodeVersion = node --version
    Write-Host "✓ Node.js $nodeVersion is installed" -ForegroundColor Green
} catch {
    Write-Host "✗ Node.js is not installed." -ForegroundColor Red
    Write-Host "  Please install Node.js 20+ from: https://nodejs.org/" -ForegroundColor Yellow
    exit 1
}

# Check if npm is available
try {
    $npmVersion = npm --version
    Write-Host "✓ npm $npmVersion is installed" -ForegroundColor Green
} catch {
    Write-Host "✗ npm is not installed." -ForegroundColor Red
    exit 1
}

# Install dependencies
Write-Host ""
Write-Host "Installing dependencies..." -ForegroundColor Yellow
npm install

if ($LASTEXITCODE -ne 0) {
    Write-Host "✗ Failed to install dependencies" -ForegroundColor Red
    exit 1
}

Write-Host "✓ Dependencies installed" -ForegroundColor Green

# Create .env.local file
Write-Host ""
Write-Host "Creating .env.local file..." -ForegroundColor Yellow

$secretsPath = Join-Path $PSScriptRoot "secrets"
$nextAuthSecret = Get-Content (Join-Path $secretsPath "nextauth_secret.txt") -Raw

$envContent = @"
# Portal Local Development Environment
# Generated by setup-portal.ps1

# API Configuration
NEXT_PUBLIC_API_BASE=http://localhost:8000
API_BASE=http://localhost:8000

# Authentication
NEXT_PUBLIC_OIDC_ISSUER=http://localhost:8080/realms/dpp
NEXT_PUBLIC_CLIENT_ID=dpp-portal
NEXTAUTH_URL=http://localhost:3000
NEXTAUTH_SECRET=$nextAuthSecret

# Public URLs
PUBLIC_KEYCLOAK_URL=http://localhost:8080/realms/dpp
PUBLIC_PORTAL_URL=http://localhost:3000
"@

$envPath = Join-Path $portalPath ".env.local"
$envContent | Out-File -FilePath $envPath -Encoding UTF8

Write-Host "✓ .env.local file created at: $envPath" -ForegroundColor Green

# Create a run script
$runScriptContent = @"
# Run Portal Development Server
# Make sure API is running first at http://localhost:8000

npm run dev
"@

$runScriptPath = Join-Path $portalPath "run.ps1"
$runScriptContent | Out-File -FilePath $runScriptPath -Encoding UTF8

Write-Host "✓ Run script created at: $runScriptPath" -ForegroundColor Green

Write-Host ""
Write-Host "════════════════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host "Portal Setup Complete!" -ForegroundColor Cyan
Write-Host "════════════════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host ""
Write-Host "To run the Portal:" -ForegroundColor Yellow
Write-Host "  1. Make sure the API is running at http://localhost:8000" -ForegroundColor White
Write-Host ""
Write-Host "  2. Run the Portal:" -ForegroundColor White
Write-Host "     cd $portalPath" -ForegroundColor Gray
Write-Host "     .\run.ps1" -ForegroundColor Gray
Write-Host ""
Write-Host "     Or manually:" -ForegroundColor White
Write-Host "     npm run dev" -ForegroundColor Gray
Write-Host ""
Write-Host "Portal will be available at: http://localhost:3000" -ForegroundColor Green
Write-Host ""

Set-Location $PSScriptRoot
