# Setup API for Local Development
# This script sets up the API Python environment and creates necessary config files

Write-Host "🔧 Setting up API for Local Development" -ForegroundColor Cyan
Write-Host ""

$apiPath = Join-Path $PSScriptRoot "api"

# Check if we're in the right directory
if (-not (Test-Path $apiPath)) {
    Write-Host "✗ API directory not found at: $apiPath" -ForegroundColor Red
    exit 1
}

Set-Location $apiPath

# Check if uv is installed
Write-Host "Checking for uv package manager..." -ForegroundColor Yellow
try {
    uv --version | Out-Null
    Write-Host "✓ uv is installed" -ForegroundColor Green
} catch {
    Write-Host "✗ uv is not installed. Installing..." -ForegroundColor Yellow
    Write-Host "  Visit: https://github.com/astral-sh/uv" -ForegroundColor Gray
    Invoke-RestMethod https://astral.sh/uv/install.ps1 | Invoke-Expression
}

# Create virtual environment
Write-Host ""
Write-Host "Creating virtual environment..." -ForegroundColor Yellow
uv venv

# Activate virtual environment
Write-Host "Activating virtual environment..." -ForegroundColor Yellow
. .venv\Scripts\Activate.ps1

# Install dependencies
Write-Host ""
Write-Host "Installing dependencies..." -ForegroundColor Yellow
uv pip install -e .

# Create .env file from secrets
Write-Host ""
Write-Host "Creating .env file..." -ForegroundColor Yellow

$secretsPath = Join-Path $PSScriptRoot "secrets"
$databaseUrl = Get-Content (Join-Path $secretsPath "database_url.txt") -Raw
# Replace 'postgres' hostname with 'localhost' for local development
$databaseUrl = $databaseUrl.Trim() -replace '@postgres:', '@localhost:'
$jwtSecret = Join-Path $secretsPath "jwt_secret.txt"
$encryptionKey = Join-Path $secretsPath "encryption_key.txt"
$minioUser = Join-Path $secretsPath "minio_root_user.txt"
$minioPass = Join-Path $secretsPath "minio_root_password.txt"
$oidcSecret = Join-Path $secretsPath "oidc_client_secret.txt"
$immudbPass = Join-Path $secretsPath "immudb_admin_password.txt"

$envContent = @"
# API Local Development Environment
# Generated by setup-api.ps1

# Database (localhost for local dev, postgres for Docker)
DATABASE_URL=$databaseUrl

# Object Storage (MinIO) - optional for local dev
MINIO_ENDPOINT=http://localhost:9000
MINIO_ACCESS_KEY_FILE=$minioUser
MINIO_SECRET_KEY_FILE=$minioPass

# Authentication
OIDC_ISSUER_URL=http://localhost:8080/realms/dpp
OIDC_AUDIENCE=dpp-api
OIDC_CLIENT_SECRET_FILE=$oidcSecret
JWT_SECRET_FILE=$jwtSecret

# Authorization
OPA_URL=http://localhost:8181/v1/data/dpp/allow

# Audit
IMMUDB_ADDR=localhost:3322
IMMUDB_PASSWORD_FILE=$immudbPass

# Encryption
ENCRYPTION_KEY_FILE=$encryptionKey

# API Server
API_HOST=localhost
API_PORT=8000
"@

$envPath = Join-Path $apiPath ".env"
$envContent | Out-File -FilePath $envPath -Encoding UTF8

Write-Host "✓ .env file created at: $envPath" -ForegroundColor Green

# Create a run script
$runScriptContent = @"
# Run API Server
# Make sure PostgreSQL is running first: docker compose -f compose.local-dev.yaml up -d

# Activate virtual environment
. .venv\Scripts\Activate.ps1

# Run the API with auto-reload
uvicorn dpp_api.main:app --host localhost --port 8000 --reload
"@

$runScriptPath = Join-Path $apiPath "run.ps1"
$runScriptContent | Out-File -FilePath $runScriptPath -Encoding UTF8

Write-Host "✓ Run script created at: $runScriptPath" -ForegroundColor Green

Write-Host ""
Write-Host "════════════════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host "API Setup Complete!" -ForegroundColor Cyan
Write-Host "════════════════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host ""
Write-Host "To run the API:" -ForegroundColor Yellow
Write-Host "  1. Make sure PostgreSQL is running:" -ForegroundColor White
Write-Host "     docker compose -f ..\compose.local-dev.yaml up -d" -ForegroundColor Gray
Write-Host ""
Write-Host "  2. Run the API:" -ForegroundColor White
Write-Host "     cd $apiPath" -ForegroundColor Gray
Write-Host "     .\run.ps1" -ForegroundColor Gray
Write-Host ""
Write-Host "     Or manually:" -ForegroundColor White
Write-Host "     . .venv\Scripts\Activate.ps1" -ForegroundColor Gray
Write-Host "     uvicorn dpp_api.main:app --host localhost --port 8000 --reload" -ForegroundColor Gray
Write-Host ""
Write-Host "API will be available at: http://localhost:8000" -ForegroundColor Green
Write-Host "API docs at: http://localhost:8000/docs" -ForegroundColor Green
Write-Host ""

Set-Location $PSScriptRoot
